# BOAS PRÁTICAS
    # FUNÇÕES E VARIAVEIS EM snake_case
    # CONSTANTES EM SNAKE_UPPER_CASE
    # CLASSES, CASO TENHA EM PascalCase 

# CNPJ DA EMPRESA -> 74.048.200/0001-50
# NOME DA EMPRESA -> DOGS HIPERMERCADO
# TELEFONE DA EMPRESA -> (79) 9 8818-7373